### ISSUE TITLE
Customizer options not saved until changed.

### ISSUE THREAD

**Issue by francoisjacquet** [PremiseWP/simplicity#1]
When activating the theme, no default customizer options are available (speaking of the added  `pwps_customizer_options` only).

When going to the customizer,
modifying some options (different from the `pwps_customizer_options`) and saving, does **not** save the default customizer options either.

Each option, for the moment, is saved individually, only when changed.

As a result, for example, the default `fa-search` `nav-icon` does not appear on front end.

**Comment by mvallejo3** [comment]
Created default options. issue resovled
